### ISSUE TITLE
Out-of-bounds warnings suppressed

### ISSUE THREAD

**Issue by ehultee** [bryanvriel/iceutils#11]
I finally fixed all apparent errors and extracted what looks like a reasonable timeseries for a point on Helheim.  Hooray!

In the course of this troubleshooting, it became apparent that the warnings you included in https://github.com/bryanvriel/iceutils/blob/master/iceutils/stack.py#L159-L167 are not being raised.  I requested out-of-bounds points in both an interactive shell and a script, and the warnings did not appear.  

Instead, the code ran with no errors and saved a timeseries as `NoneType`, leading to confusing error messages later on.  Figuring out what's up with these warnings will make the package more user-friendly.

**Comment by bryanvriel** [comment]
I've re-ran some tests on the Helheim stack, and the warnings are being raised as expected. The latest commit (a94ce9acacf26898cfa7957357be0f5c9cb05b67) also modifies the out-of-bounds return to be a NaN-filled array with the same length as the expected time series.
