### ISSUE TITLE
MagStack.timeseries failing in get_chunk

### ISSUE THREAD

**Issue by ehultee** [bryanvriel/iceutils#6]
I am initializing a MagStack and trying to take a time series from it.  Here is the script:
```
## Set up combined hdf5 stack
fpath='/home/ehultee/Stack/'
hel_stack = ice.MagStack(files=[fpath+'vx.h5', fpath+'vy.h5'])

## Extract time series at a point
xy_1 = (305.0, -2578.0) #polar stereo coordinates of a point near Helheim 2009 terminus
d = hel_stack.timeseries(xy=xy_1)
print(type(d))
```

When I run this, I get a TypeError:
```
Traceback (most recent call last):
  File "helheim-extract_ts.py", line 14, in <module>
    d = hel_stack.timeseries(xy=xy_1)
  File "/home/ehultee/.conda/envs/ehu-gld/lib/python3.7/site-packages/iceutils/stack.py", line 329, in timeseries
    dsum += (stack.timeseries(xy=xy, coord=coord, key=key, win_size=win_size))**2
TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'int'
```

I suspect that one of the slices is empty for one or more of the time points.  I will check at other extraction coords and using only a single Stack (rather than a MagStack).  If I am correct, this means that we need to do error handling for points close to termini where there may be data only before (or after) a certain time horizon.

**Comment by BryanRiel** [comment]
That can also happen if a point is requested outside of the bounds of the Stack, e.g. check lines 158-161 in `stack.py`. You might want to try converting the values in `xy_1` to meters. Either way, better error handling is definitely in order.
